### ISSUE TITLE
Show the user that there is still a cooldown for OTP

### ISSUE THREAD

**Issue by proffapt** [metakgp/heimdall#13]
- User requests the OTP
- In frontend a timer starts in-place of the content of `request otp` button
- The button is disabled till the timer hits 0
- Button content changes to `resend otp` and the button is now clickable

**Comment by Dami-18** [comment]
What is the issue exactly? Can I work on it?

**Comment by proffapt** [comment]
So the issue is:

If you have requested for OTP, you can't request for another till 1 minute cooldown timeout. This is implemented in backend but the user won't know from frontend and when they try to request it again within that timeframe they receive this generic error message "Failed to send the OTP". 

Sure go ahead and just present the actual error received from the backend.

**Comment by Dami-18** [comment]
Facing issues in setup. Heimdall server is running on port 3333 but when I enter my mail Id and click generate otp, it is not able to find credentials.json file

**Comment by Dami-18** [comment]
So not getting otp even for the first time

**Comment by proffapt** [comment]
have you configured Gmail api credentials?

**Comment by proffapt** [comment]
The documentation is not updated. cc @rohan-b-84 @chirag-ghosh

**Comment by Dami-18** [comment]
> have you configured Gmail api credentials?

How do I do that?

**Comment by Dami-18** [comment]
Ok I am following instructions given on iitkgp-erp-login library

**Comment by Dami-18** [comment]
But why is it working without any configuration on the hosted site?

**Comment by rohan-b-84** [comment]
@proffapt updating documentation itself is an issue https://github.com/metakgp/heimdall/issues/11

@Dami-18 to get credentials.json file
first create the [OAuth consent screen](https://developers.google.com/workspace/guides/configure-oauth-consent) and then [create OAuth client ID credentials](https://developers.google.com/workspace/guides/create-credentials#oauth-client-id) and save the downloaded json as `credentials.json` in the project's root folder.

If you get through this, can you also take #11 as well ?

**Comment by chirag-ghosh** [comment]
@Dami-18 it is working on the hosted site because it has those files. We add them to the server when we set it up. A better documentation will make things clear.

**Comment by Dami-18** [comment]
> @proffapt updating documentation itself is an issue #11
> 
> @Dami-18 to get credentials.json file first create the [OAuth consent screen](https://developers.google.com/workspace/guides/configure-oauth-consent) and then [create OAuth client ID credentials](https://developers.google.com/workspace/guides/create-credentials#oauth-client-id) and save the downloaded json as `credentials.json` in the project's root folder.
> 
> If you get through this, can you also take #11 as well ?

Ok once I am able to successfully run the dev server, I will update documentation too

**Comment by proffapt** [comment]
There's an issue corresponding to documentation #11

**Comment by Dami-18** [comment]
I got the credentials.json file but after running server, when it says go to following link and enter the authentication code, it always says refused to connect or invalid request after clicking on the link. I tried changing redirect urls and checked network also but still facing same error. What could be the possible issue?

**Comment by chirag-ghosh** [comment]
When it redirects, the url will redirect to localhost and will contain the code in the url parameters itself. `?code=something` ig. That _something_ is the code you need to paste in the terminal.
I know this is a really janky way to do but once that token.json is created, It'll be valid for 6months so I didn't care about it much

**Comment by Dami-18** [comment]
Also @proffapt new version of erp-login package expected to release when? We need to complete gyfe and gyft before subject registration

**Comment by proffapt** [comment]
> Also [@proffapt](https://github.com/proffapt) new version of erp-login package expected to release when? We need to complete gyfe and gyft before subject registration

https://metakgp.slack.com/archives/C05KTAL5ARM/p1719258932859839
