### ISSUE TITLE
Make frontend responsive

### ISSUE THREAD

**Issue by proffapt** [metakgp/heimdall#16]
<img height=600px src="https://github.com/metakgp/heimdall/assets/86282911/fbadedb7-c8d7-4e19-9d94-d4c9efe0a18a">

**Comment by Ananya-m0140** [comment]
I want to work on this issue.

**Comment by proffapt** [comment]
Try to finish it as soon as possible. Provide updates on the status by 12 noon tomorrow. It's urgent.

**Comment by proffapt** [comment]
Fixed in https://github.com/metakgp/heimdall/commit/7bbed78ee3808cca86ca50ad93844057a7d66f3f
