### ISSUE TITLE
Frontend for providing single source of authentication logic for kgpians

### ISSUE THREAD

**Issue by rohan-b-84** [metakgp/heimdall#6]
The plan:

- [ ] Takes `*@kgpian.iitkgpl.ac.in` or `*@iitkgp.ac.in` only
- [ ] Sends OTP, user enters the otp to authorise it
- [ ] Display a list of services implementing auth
- [ ] Whenever user clicks these button, the request will be sent to relevant projects with a Auth Bearer token (generated via backend)
- [ ] Other services will be configured to be accessible when that Bearer token exist (first such implementation will be for [naarad](https://github.com/metakgp/naarad/issues/3))

Refer #4

**Comment by proffapt** [comment]
@rohan-b-84 @chirag-ghosh ye issue bhi close kardena hai?

**Comment by proffapt** [comment]
Implemented in #5
